variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test_51510
  - test_624
  - test_642
  - test_653
  - test_66
  - test_67
  - test_68

Test_51510:
  stage: test_51510
  image:
    name: "carlonluca/qt-dev:5.15.10-lts-lgpl"
    entrypoint: [""]
  script:
    - cd tests/Fall_qt5
    - mkdir build
    - cd build
    - export PATH=/opt/Qt-amd64-5.15.10-lts-lgpl/bin:$PATH
    - cmake ..
    - make
    - cd ..
    - rm -rf build
    - mkdir build
    - cd build
    #- export PATH=/opt/Qt-and-armv7a-5.15.10-lts-lgpl/bin:$PATH
    #- cmake ..
    #- make
    #- test -f ./android-build/build/outputs/apk/debug/android-build-debug.apk
    #- cd ../../SslCheck
    #- mkdir build
    #- cd build
    #- cmake ..

Test_624:
  stage: test_624
  image:
    name: "carlonluca/qt-dev:6.2.4_jammy"
    entrypoint: [""]
  script:
    - cd tests/Fall
    - mkdir build
    - cd build
    - /opt/Qt-amd64-6.2.4/bin/qt-cmake ..
    - make

Test_642:
  stage: test_642
  image:
    name: "carlonluca/qt-dev:6.4.2"
    entrypoint: [""]
  script:
    - cd tests/Fall
    - mkdir build
    - cd build
    - /opt/Qt-amd64-6.4.2/bin/qt-cmake ..
    - make
    - cd ..
    - rm -rf build
    - mkdir build
    - cd build
    - /opt/Qt-and-armv7a-6.4.2/bin/qt-cmake ..
    - make
    - test -f ./android-build/build/outputs/apk/debug/android-build-debug.apk
    - cd ../../SslCheck
    - mkdir build
    - cd build
    - /opt/Qt-and-armv7a-6.4.2/bin/qt-cmake ..

Test_653:
  stage: test_653
  image:
    name: "carlonluca/qt-dev:6.5.3"
    entrypoint: [""]
  script:
    - cd tests/Fall
    - mkdir build
    - cd build
    - /opt/Qt-amd64-6.5.3/bin/qt-cmake ..
    - make
    - cd ..
    - rm -rf build
    - mkdir build
    - cd build
    - /opt/Qt-android-6.5.3/android_x86/bin/qt-cmake ..
    - make
    - test -f ./android-build/build/outputs/apk/debug/android-build-debug.apk
    - cd ../../SslCheck
    - mkdir build
    - cd build
    - /opt/Qt-android-6.5.3/android_x86/bin/qt-cmake ..

Test_66:
  stage: test_66
  image:
    name: "carlonluca/qt-dev:6.6.3"
    entrypoint: [""]
  script:
    - cd tests/Fall
    - mkdir build
    - cd build
    - /opt/Qt-amd64-6.6.3/bin/qt-cmake ..
    - make
    - cd ..
    - rm -rf build
    - mkdir build
    - cd build
    - /opt/Qt-android-6.6.3/android_x86/bin/qt-cmake ..
    - make
    - test -f ./android-build/build/outputs/apk/debug/android-build-debug.apk
    - cd ../../SslCheck
    - mkdir build
    - cd build
    - /opt/Qt-android-6.6.3/android_x86/bin/qt-cmake ..

Test_67:
  stage: test_67
  image:
    name: "carlonluca/qt-dev:6.7.3"
    entrypoint: [""]
  script:
    - cd tests/Fall
    - mkdir build
    - cd build
    - /opt/Qt-amd64-6.7.3/bin/qt-cmake ..
    - make
    - cd ..
    - rm -rf build
    - mkdir build
    - cd build
    - /opt/Qt-android-6.7.3/android_x86/bin/qt-cmake ..
    - make
    - test -f ./android-build/build/outputs/apk/debug/android-build-debug.apk
    - cd ../../SslCheck
    - mkdir build
    - cd build
    - /opt/Qt-android-6.7.3/android_x86/bin/qt-cmake ..

Test_68:
  stage: test_68
  image:
    name: "carlonluca/qt-dev:6.8.1"
    entrypoint: [""]
  script:
    - cd tests/Fall
    - mkdir build
    - cd build
    - /opt/Qt-amd64-6.8.1/bin/qt-cmake ..
    - make
    - cd ..
    - rm -rf build
    - mkdir build
    - cd build
    - /opt/Qt-android-6.8.1/android_x86/bin/qt-cmake ..
    - make
    - test -f ./android-build/build/outputs/apk/debug/android-build-debug.apk
    - cd ../../SslCheck
    - mkdir build
    - cd build
    - /opt/Qt-android-6.8.1/android_x86/bin/qt-cmake ..