variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test_51510
  - test_5158_cleanup
  - test_624
  - test_624_cleanup
  - test_642
  - test_642_cleanup
  - test_653
  - test_653_cleanup
  - test_660
  - test_660_cleanup

Test_51510:
  stage: test_51510
  image:
    name: "carlonluca/qt-dev:5.15.10-lts-lgpl"
    entrypoint: [""]
  script:
    - cd tests/Fall
    - mkdir build
    - cd build
    - export PATH=/opt/Qt-amd64-5.15.10-lts-lgpl/bin:$PATH
    - cmake ..
    - make
    - cd ..
    - rm -rf build
    - mkdir build
    - cd build
    #- export PATH=/opt/Qt-and-armv7a-5.15.10-lts-lgpl/bin:$PATH
    #- cmake ..
    #- make
    #- test -f ./android-build/build/outputs/apk/debug/android-build-debug.apk
    #- cd ../../SslCheck
    #- mkdir build
    #- cd build
    #- cmake ..

Test_5158_cleanup:
  stage: test_5158_cleanup
  script:
    - docker image rm carlonluca/qt-dev:5.15.8-lts-lgpl || true

Test_624:
  stage: test_624
  image:
    name: "carlonluca/qt-dev:6.2.4_jammy"
    entrypoint: [""]
  script:
    - cd tests/Fall
    - mkdir build
    - cd build
    - /opt/Qt-amd64-6.2.4/bin/qt-cmake ..
    - make

Test_624_cleanup:
  stage: test_624_cleanup
  script:
    - docker image rm carlonluca/qt-dev:6.2.4 || true

Test_642:
  stage: test_642
  image:
    name: "carlonluca/qt-dev:6.4.2"
    entrypoint: [""]
  script:
    - cd tests/Fall
    - mkdir build
    - cd build
    - /opt/Qt-amd64-6.4.2/bin/qt-cmake ..
    - make
    - cd ..
    - rm -rf build
    - mkdir build
    - cd build
    - /opt/Qt-and-armv7a-6.4.2/bin/qt-cmake ..
    - make
    - test -f ./android-build/build/outputs/apk/debug/android-build-debug.apk
    - cd ../../SslCheck
    - mkdir build
    - cd build
    - /opt/Qt-and-armv7a-6.4.2/bin/qt-cmake ..

Test_642_cleanup:
  stage: test_642_cleanup
  script:
    - docker image rm carlonluca/qt-dev:6.4.2 || true

Test_653:
  stage: test_653
  image:
    name: "carlonluca/qt-dev:6.5.3"
    entrypoint: [""]
  script:
    - cd tests/Fall
    - mkdir build
    - cd build
    - /opt/Qt-amd64-6.5.3/bin/qt-cmake ..
    - make
    - cd ..
    - rm -rf build
    - mkdir build
    - cd build
    - /opt/Qt-android-6.5.3/android_x86/bin/qt-cmake ..
    - make
    - test -f ./android-build/build/outputs/apk/debug/android-build-debug.apk
    - cd ../../SslCheck
    - mkdir build
    - cd build
    - /opt/Qt-android-6.5.3/android_x86/bin/qt-cmake ..

Test_653_cleanup:
  stage: test_653_cleanup
  script:
    - docker image rm carlonluca/qt-dev:6.5.3 || true

Test_660:
  stage: test_660
  image:
    name: "carlonluca/qt-dev:6.6.0"
    entrypoint: [""]
  script:
    - cd tests/Fall
    - mkdir build
    - cd build
    - /opt/Qt-amd64-6.6.0/bin/qt-cmake ..
    - make
    - cd ..
    - rm -rf build
    - mkdir build
    - cd build
    - /opt/Qt-android-6.6.0/android_x86/bin/qt-cmake ..
    - make
    - test -f ./android-build/build/outputs/apk/debug/android-build-debug.apk
    - cd ../../SslCheck
    - mkdir build
    - cd build
    - /opt/Qt-android-6.6.0/android_x86/bin/qt-cmake ..

Test_660_cleanup:
  stage: test_660_cleanup
  script:
    - docker image rm carlonluca/qt-dev:6.6.0 || true
