variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test_642_linux
  - test_642_android

Test_642_linux:
  stage: test_642_linux
  image:
    name: "carlonluca/qt-dev:6.4.2"
    entrypoint: [""]
  script:
    - cd tests/Fall
    - mkdir build
    - cd build
    - /opt/Qt-amd64-6.4.2/bin/qt-cmake ..
    - make

Test_642_android:
  stage: test_642_android
  image:
    name: "carlonluca/qt-dev:6.4.2"
    entrypoint: [""]
  script:
    - cd tests/Fall
    - mkdir build
    - cd build
    - /opt/Qt-and-armv7a-6.4.2/bin/qt-cmake ..
    - make
    - test -f ./android-build/build/outputs/apk/debug/android-build-debug.apk
