name: Test
on: push

jobs:
  test_5158:
    runs-on: ubuntu-22.04
    container:
      image: docker.io/carlonluca/qt-dev:5.15.8-lts-lgpl
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        shell: bash
        run: |
          cd tests/Fall
          mkdir build
          cd build
          export PATH=/opt/Qt-amd64-5.15.8-lts-lgpl/bin:$PATH
          cmake ..
          make
          cd ..
          rm -rf build
          mkdir build
          cd build