name: Test
on: push

jobs:
  test_5158:
    runs-on: ubuntu-22.04
    container:
      image: docker.io/carlonluca/qt-dev:5.15.10-lts-lgpl
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        shell: bash
        run: |
          cd tests/Fall_qt5
          mkdir build
          cd build
          export PATH=/opt/Qt-amd64-5.15.10-lts-lgpl/bin:$PATH
          cmake ..
          make
          cd ..
          rm -rf build
          mkdir build
          cd build
  test_624:
    runs-on: ubuntu-22.04
    container:
      image: docker.io/carlonluca/qt-dev:6.2.4_jammy
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        shell: bash
        run: |
          cd tests/Fall
          mkdir build
          cd build
          /opt/Qt-amd64-6.2.4/bin/qt-cmake ..
          make
  test_642:
    runs-on: ubuntu-22.04
    container:
      image: docker.io/carlonluca/qt-dev:6.4.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        shell: bash
        run: |
          cd tests/Fall
          mkdir build
          cd build
          /opt/Qt-amd64-6.4.2/bin/qt-cmake ..
          make
          cd ..
          rm -rf build
          mkdir build
          cd build
          /opt/Qt-and-armv7a-6.4.2/bin/qt-cmake ..
          make
          test -f ./android-build/build/outputs/apk/debug/android-build-debug.apk
          cd ../../SslCheck
          mkdir build
          cd build
          /opt/Qt-and-armv7a-6.4.2/bin/qt-cmake ..
  test_65:
    runs-on: ubuntu-22.04
    container:
      image: docker.io/carlonluca/qt-dev:6.5.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        shell: bash
        run: |
          cd tests/Fall
          mkdir build
          cd build
          /opt/Qt-amd64-6.5.2/bin/qt-cmake ..
          make
          cd ..
          rm -rf build
          mkdir build
          cd build
          /opt/qt/6.5.2/android_arm64_v8a/bin/qt-cmake ..
          make
          test -f ./android-build/build/outputs/apk/debug/android-build-debug.apk
          cd ../../SslCheck
          mkdir build
          cd build
          /opt/qt/6.5.2/android_arm64_v8a/bin/qt-cmake ..
  test_66:
    runs-on: ubuntu-22.04
    container:
      image: docker.io/carlonluca/qt-dev:6.6.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        shell: bash
        run: |
          cd tests/Fall
          mkdir build
          cd build
          /opt/Qt-amd64-6.6.2/bin/qt-cmake ..
          make
          cd ..
          rm -rf build
          mkdir build
          cd build
          /opt/qt/6.6.2/android_arm64_v8a/bin/qt-cmake ..
          cmake
          test -f ./android-build/build/outputs/apk/debug/android-build-debug.apk
          cd ../../SslCheck
          mkdir build
          cd build
          /opt/qt/6.6.2/android_arm64_v8a/bin/qt-cmake ..